### PR TITLE
CloudObject subclassing support and embedded framework target

### PR DESCRIPTION
**Pull request by MicheleLonghi**
### CloudObject subclassing support
This update allows to obtain objects of a custom subclass  from CloudSearch.search

Example:
```
class Invoice: CloudObject {
    var totalAmount: Double {
        get {
            return get("totalAmount") as? Double ?? 0.0
        }
        set {
            return set("totalAmount", newValue)
        }
    }
}

CloudSearch(tableName: "Invoice", objectClass: Invoice.self)
    .search { (response) in
                
        if let invoices = response.object as? [Invoice] {
            let firstInvoice = invoices.first!
            let amount = firstInvoice.totalAmount
        }
    }
``` 
If no objectClass parameter is given, search will behave has usual, returning CloudObject items. 

### Embedded framework target
A new targed cloudboost-embedded has been added. Basically it doesn't contain cocoapods references and can be embedded directly in parent projects. Cocoapods is still present and continues to use the default CloudBoost target.

### CODE REVIEW

**Comment by MicheleLonghi** [comment]
Added subclassing support for queries and object notifications.
Now related object are returned as CloudObjects instead as NSDictionaries

**Comment by MicheleLonghi** [comment]
commit ea4c8e4 introduces a new feature allowing to map table name with CloudObject subclasses.

Example:

``` swift
CloudApp.objectsMapping = [
    "User": myAppUser.self,
    "Invoice": InvoiceObject,
    "Customer": CustomerObject
]

let query = CloudQuery(tableName: "Invoice")
query.find { response in
   print(response.object) // Result: [InvoiceObject]
}
```
It works for relations, query, search and object notifications.

If not specified default classes are used. Default classes are also for table names not included into the dictionary.

**Comment by MicheleLonghi** [comment]
Last commit introduces dedicated accessors for NSDecimalNumbers. It is advisable for currency rounding to use these dedicated methods.

**Comment by nawazdhandala** [comment]
Thank you. We'll review it and let you know. :)

**Comment by nawazdhandala** [comment]
These are good meaty contributions. I'm reviewing the code, let me get back to you real quick.

**Comment by MicheleLonghi** [comment]
They're functionalities necessary for us, so I think could be useful for others.

**Comment by MicheleLonghi** [comment]
Starting to comment code in Xcode auto-documentation style

**Comment by MicheleLonghi** [comment]
new methods getDouble and setDouble

**Pull request merged**
